{% set name = "uptrace" %}
{% set version = "1.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uptrace-{{ version }}.tar.gz
  sha256: 0b10bb1c10074505519b7625b7987016d589da41c38470b524f716a540915904

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.37.0,<1.38.dev0
    - opentelemetry-sdk >=1.37.0,<1.38.dev0
    - opentelemetry-exporter-otlp >=1.37.0,<1.38.dev0
    - opentelemetry-instrumentation >=0.58b0,<1.dev0

test:
  imports:
    - uptrace
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://uptrace.dev
  summary: OpenTelemetry Python distribution for Uptrace
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
