{% set name = "uptrace" %}
{% set version = "1.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uptrace-{{ version }}.tar.gz
  sha256: cb747d61281adc58110ca4a53cdc36a20fbb3d346f0661a9352c942bffdb43dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.39.0,<1.40.dev0
    - opentelemetry-sdk >=1.39.0,<1.40.dev0
    - opentelemetry-exporter-otlp >=1.39.0,<1.40.dev0
    - opentelemetry-instrumentation >=0.60b1,<0.61a0

test:
  imports:
    - uptrace
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://uptrace.dev
  summary: OpenTelemetry Python distribution for Uptrace
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
